In [1]:
from pymongo import MongoClient

In [2]:
mongo = MongoClient(
    "mongodb+srv://hamidovaslon1:nPxcKaGrRkAwxiek@cluster0.4w1m4jc.mongodb.net/?retryWrites=true&w=majority"   
)

In [16]:
import pandas as pd
activities=list(list(mongo["magazin"]["activities"].find()))
df = pd.DataFrame(
    data=list(list(mongo["magazin"]["activities"].find()))
).sort_values(by="date", ascending=True)
df

,_id,user_id,action,data,ip,date,status
215,686a757c28cd39427826c572,aslon,create_journal,{'branchnameorid': 'aadee444-306d-48e1-aa5c-50...,172.18.0.1,2025-07-06 13:09:16.214,200
186,686a758828cd39427826c574,aslon,create_journal,{'branchnameorid': 'aadee444-306d-48e1-aa5c-50...,172.18.0.1,2025-07-06 13:09:28.362,200
216,686a79c167136bc57831a523,aslon,login_success,{'error': 'Invalid password'},172.18.0.1,2025-07-06 13:27:29.938,200
0,686a79c667136bc57831a524,aslon,login_success,{'error': 'Invalid password'},172.18.0.1,2025-07-06 13:27:34.412,200
73,686a8cc167136bc57831a525,jaloliddin,login_success,{'error': 'Invalid password'},172.18.0.1,2025-07-06 14:48:33.025,200
...,...,...,...,...,...,...,...
6304,6a1b074110b6126747f91390,umidx,create_transaction,"{'transactionbase': {'amount': 1200000, 'descr...",100.64.0.15,2026-05-30 15:50:25.249,200
6305,6a1b07ec10b6126747f91391,umidx,create_transaction,"{'transactionbase': {'amount': 1200000, 'descr...",100.64.0.7,2026-05-30 15:53:16.650,200
6306,6a1b083c10b6126747f91392,umidx,close_journal,"{'journal_id': '6a1aa93010b6126747f91383', 'ca...",100.64.0.7,2026-05-30 15:54:36.310,200
6307,6a1bc84f5356e2d87e322a02,umidx,create_journal,{'branchnameorid': 'aadee444-306d-48e1-aa5c-50...,100.64.0.13,2026-05-31 05:34:07.397,200
6308,6a1bc8635356e2d87e322a03,umidx,create_transaction,"{'transactionbase': {'amount': 130000, 'descri...",100.64.0.13,2026-05-31 05:34:27.519,200

In [27]:
df[df["action"] == "create_journal" ]["data"].values

array([{'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 6, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 7, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 7, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 7, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 7, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 8, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 8, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 9, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 9, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 9, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 9, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 9, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 9, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 9, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 9, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 9, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 9, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 9, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 9, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 9, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 9, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 9, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 10, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 10, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 10, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 12, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 12, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 13, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 13, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 14, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 15, 0, 0)},
       {'branchnameorid': 'Polevoy', 'date': datetime.datetime(2025, 7, 14, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 14, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 14, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 14, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 14, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 15, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 15, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 16, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 16, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 17, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 17, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 17, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 17, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 17, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 17, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 18, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 18, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 18, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 19, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 19, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 20, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 20, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 21, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 21, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 22, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 22, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 23, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 23, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 23, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 23, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 23, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 23, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 23, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 23, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 24, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 24, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 24, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 25, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 25, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 26, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 26, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 27, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 27, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 28, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 28, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 29, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 29, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 30, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 30, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 7, 31, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 7, 31, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 1, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 1, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 2, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 2, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 2, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 2, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 3, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 3, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 3, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 4, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 4, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 5, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 5, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 6, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 6, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 6, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 6, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 7, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 7, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 8, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 8, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 8, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 9, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 9, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 10, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 10, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 10, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 10, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': '2dbbbb13-60be-425e-b07c-fa4889f0400d', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},
       {'branchnameorid': 'aadee444-306d-48e1-aa5c-501b86a584be', 'date': datetime.datetime(2025, 8, 11, 0, 0)},

In [28]:
mongo["magazin"]['finance'].insert_many(
    [
{
  "finance": {
    "balance": {
      "cash": 143000000,
      "bank": 56500000,
      "terminal": 2000000,
      "mobile_apps": 1705000
    },
    "total_income": 0,
    "total_expenses": 0,
    "debt": 29500000
  },
  "suppliers": [
    "0cb250aa-14e5-4b64-97a3-85541c2baa41",
    "6010a885-181f-4267-8600-546956f2f1c3",
    "e0fa072d-4903-4f05-8a4f-94b3f25a29d1"
  ],
  "branch_id": "aadee444-306d-48e1-aa5c-501b86a584be",
  "branch_name": "Xonobod",
  "details": {
    "location": "Location A"
  },
  "total": -1000000
},
{
  "finance": {
    "balance": {
      "cash": 0,
      "bank": 0,
      "terminal": 0,
      "mobile_apps": 0
    },
    "total_income": 0,
    "total_expenses": 0,
    "debt": 0
  },
  "suppliers": [
    "a16f2521-6dde-4b39-8985-8ebd9b36b171",
    "50c20e0b-6243-486e-952f-84e5581429d3"
  ],
  "branch_id": "2dbbbb13-60be-425e-b07c-fa4889f0400d",
  "branch_name": "Polevoy",
  "details": {
    "location": "Location B"
  }
}
    ]
)

InsertManyResult([ObjectId('6a1be907e39f29b3dbc8eb88'), ObjectId('6a1be907e39f29b3dbc8eb89')], acknowledged=True)

In [33]:
transactions["user_id"].value_counts()

user_id
asadx         1744
umidx         1261
saloh          388
jaloliddin     383
aslon          235
dostonyh        30
Name: count, dtype: int64

In [31]:
# create transactions
transactions = df[df["action"] == "create_transaction"]
transactions["data"].values

array([{'transactionbase': {'amount': 50000, 'description': 'Click ', 'type': 'credit', 'payment_method': 'cash'}, 'supplier_transaction': False, 'supplier_id': ''},
       {'transactionbase': {'amount': 270000, 'description': 'Click ', 'type': 'credit', 'payment_method': 'cash'}, 'supplier_transaction': False, 'supplier_id': ''},
       {'transactionbase': {'amount': 140000, 'description': 'Click ', 'type': 'credit', 'payment_method': 'cash'}, 'supplier_transaction': False, 'supplier_id': ''},
       ...,
       {'transactionbase': {'amount': 1200000, 'description': 'Click ', 'type': 'credit', 'payment_method': 'cash'}, 'supplier_transaction': False, 'supplier_id': ''},
       {'transactionbase': {'amount': 1200000, 'description': 'Selsil firmaga ', 'type': 'credit', 'payment_method': 'cash'}, 'supplier_transaction': False, 'supplier_id': ''},
       {'transactionbase': {'amount': 130000, 'description': 'Click ', 'type': 'credit', 'payment_method': 'cash'}, 'supplier_transaction': False, 'supplier_id': ''}],
      shape=(4041,), dtype=object)

In [50]:
df[df["action"] == "close_journal"]["data"].values

array([{'journal_id': '6869fbfd45fa4aec21b5a847', 'cash_left': '1000', 'terminal_income': '1000'},
       {'journal_id': '6869fbfd45fa4aec21b5a847', 'cash_left': '1000', 'terminal_income': '1000'},
       {'cash_left': '1000', 'terminal_income': '1000', 'journal_id': '6869fbfd45fa4aec21b5a847'},
       {'journal_id': '6869fbfd45fa4aec21b5a847', 'cash_left': '1000', 'terminal_income': '1000'},
       {'cash_left': '6250000', 'terminal_income': '2200000', 'journal_id': '6869fbfd45fa4aec21b5a847'},
       {'cash_left': '5700000', 'terminal_income': '3100000', 'journal_id': '6869fbfd45fa4aec21b5a847'},
       {'journal_id': '686a214245fa4aec21b5a848', 'cash_left': '6250000', 'terminal_income': '2200000'},
       {'cash_left': '8790000', 'terminal_income': '2200000', 'journal_id': '686a214245fa4aec21b5a848'},
       {'journal_id': '6868f7b545fa4aec21b5a845', 'cash_left': '1000', 'terminal_income': '1000'},
       {'journal_id': '686b75242eb8830a3bb46e9b', 'cash_left': '1900000', 'terminal_income': '3226000'},
       {'journal_id': '686b36d32eb8830a3bb46e92', 'cash_left': '5650000', 'terminal_income': '1600000'},
       {'journal_id': '686cdc0d2eb8830a3bb46eb1', 'cash_left': '3300000', 'terminal_income': '2030000'},
       {'journal_id': '686d02992eb8830a3bb46ec1', 'cash_left': '6860000', 'terminal_income': '1500000'},
       {'cash_left': '3300000', 'terminal_income': '2030000', 'journal_id': '686cdc0d2eb8830a3bb46eb1'},
       {'journal_id': '686e63212eb8830a3bb46ee6', 'cash_left': '8060000', 'terminal_income': '2900000'},
       {'journal_id': '686de4522eb8830a3bb46ed6', 'cash_left': '8060000', 'terminal_income': '2900000'},
       {'journal_id': '686e63212eb8830a3bb46ee6', 'cash_left': '8060000', 'terminal_income': '2900000'},
       {'cash_left': '7436000', 'terminal_income': '2900000', 'journal_id': '686e63212eb8830a3bb46ee6'},
       {'terminal_income': '2080000', 'journal_id': '686de4522eb8830a3bb46ed6', 'cash_left': '20000'},
       {'journal_id': '686f58722eb8830a3bb46f14', 'cash_left': '1550000', 'terminal_income': '1681000'},
       {'journal_id': '686f5f152eb8830a3bb46f17', 'cash_left': '2650000', 'terminal_income': '4700000'},
       {'journal_id': '686f58722eb8830a3bb46f14', 'cash_left': '155000', 'terminal_income': '1681000'},
       {'journal_id': '686f58722eb8830a3bb46f14', 'cash_left': '1550000', 'terminal_income': '1650000'},
       {'terminal_income': '1680000', 'journal_id': '686f58722eb8830a3bb46f14', 'cash_left': '1550000'},
       {'journal_id': '6870be242eb8830a3bb46f53', 'cash_left': '350000', 'terminal_income': '1300000'},
       {'journal_id': '6870d6a12eb8830a3bb46f58', 'cash_left': '6096000', 'terminal_income': '1885000'},
       {'journal_id': '6870d6a12eb8830a3bb46f58', 'cash_left': '6096000', 'terminal_income': '1885000'},
       {'terminal_income': '1800000', 'journal_id': '687201cc2eb8830a3bb46f70', 'cash_left': '400000'},
       {'terminal_income': '2835000', 'journal_id': '6871d5322eb8830a3bb46f6c', 'cash_left': '6070000'},
       {'journal_id': '6864b5e95dfc7f1ed81b8b91', 'cash_left': '11111', 'terminal_income': '111111'},
       {'journal_id': '687364842eb8830a3bb46f8c', 'cash_left': '9150000', 'terminal_income': '1700000'},
       {'journal_id': '6873c8682eb8830a3bb46f95', 'cash_left': '8100000', 'terminal_income': '1700000'},
       {'journal_id': '6873c8682eb8830a3bb46f95', 'cash_left': '1700000', 'terminal_income': '8100000'},
       {'journal_id': '6874ab522eb8830a3bb46fa2', 'cash_left': '1', 'terminal_income': '1'},
       {'journal_id': '6874ab522eb8830a3bb46fa2', 'cash_left': '5560000', 'terminal_income': '1400000'},
       {'journal_id': '6874b77f2eb8830a3bb46fa9', 'cash_left': '5560000', 'terminal_income': '1700000'},
       {'journal_id': '6874ab522eb8830a3bb46fa2', 'cash_left': '4700000', 'terminal_income': '2850000'},
       {'journal_id': '6875e3952eb8830a3bb46fc0', 'cash_left': '200000', 'terminal_income': '2200000'},
       {'journal_id': '687621f02eb8830a3bb46fc8', 'cash_left': '3000000', 'terminal_income': '3000000'},
       {'journal_id': '687621f02eb8830a3bb46fc8', 'cash_left': '3000000', 'terminal_income': '5540000'},
       {'cash_left': '5360000', 'terminal_income': '3400000', 'journal_id': '68776c6e615a08965061f57f'},
       {'journal_id': '687754ac615a08965061f578', 'cash_left': '2400000', 'terminal_income': '1300000'},
       {'journal_id': '6878a026615a08965061f58f', 'cash_left': '6820000', 'terminal_income': '2425000'},
       {'journal_id': '6878a497615a08965061f59d', 'cash_left': '8100000', 'terminal_income': '1550000'},
       {'journal_id': '687a3e81615a08965061f5b4', 'cash_left': '4785000', 'terminal_income': '1800000'},
       {'journal_id': '6879e07f615a08965061f5af', 'cash_left': '2500000', 'terminal_income': '1884000'},
       {'journal_id': '687b60bd615a08965061f5d8', 'cash_left': '10000000', 'terminal_income': '2300000'},
       {'journal_id': '687b41de615a08965061f5d4', 'cash_left': '8900000', 'terminal_income': '2700000'},
       {'cash_left': '9070000', 'terminal_income': '1800000', 'journal_id': '687c4a60615a08965061f5ec'},
       {'journal_id': '687c8ac4615a08965061f5ef', 'cash_left': '9070000', 'terminal_income': '1800000'},
       {'journal_id': '687c4a60615a08965061f5ec', 'cash_left': '8625000', 'terminal_income': '2700000'},
       {'journal_id': '687de28e615a08965061f603', 'cash_left': '6360000', 'terminal_income': '2000000'},
       {'journal_id': '687e042d615a08965061f607', 'cash_left': '9100000', 'terminal_income': '3527000'},
       {'journal_id': '687f4911615a08965061f612', 'cash_left': '3250000', 'terminal_income': '2215000'},
       {'journal_id': '687f4985615a08965061f618', 'cash_left': '9340000', 'terminal_income': '2000000'},
       {'journal_id': '687f4985615a08965061f618', 'cash_left': '9340000', 'terminal_income': '2000000'},
       {'journal_id': '6874bb882eb8830a3bb46fab', 'cash_left': '1', 'terminal_income': '1'},
       {'journal_id': '6880736e615a08965061f629', 'cash_left': '4250000', 'terminal_income': '9016000'},
       {'journal_id': '68809b44615a08965061f634', 'cash_left': '3685000', 'terminal_income': '600000'},
       {'cash_left': '10850000', 'terminal_income': '800000', 'journal_id': '6881d75c615a08965061f653'},
       {'journal_id': '68820508615a08965061f65b', 'cash_left': '7250000', 'terminal_income': '2660000'},
       {'journal_id': '68831ed3b0b52d2e447eb261', 'cash_left': '9650000', 'terminal_income': '146000'},
       {'journal_id': '68831e60b0b52d2e447eb25c', 'cash_left': '4300000', 'terminal_income': '5400000'},
       {'journal_id': '68831ed3b0b52d2e447eb261', 'cash_left': '9650000', 'terminal_income': '1460000'},
       {'journal_id': '68846c97b0b52d2e447eb271', 'cash_left': '10000', 'terminal_income': '765000'},
       {'journal_id': '6884b4fdb0b52d2e447eb278', 'cash_left': '250000', 'terminal_income': '1600000'},
       {'journal_id': '68846c97b0b52d2e447eb271', 'cash_left': '100000', 'terminal_income': '765000'},
       {'cash_left': '13620000', 'terminal_income': '1650000', 'journal_id': '6885a9dcb0b52d2e447eb28e'},
       {'journal_id': '6885e582b0b52d2e447eb2a0', 'cash_left': '9800000', 'terminal_income': '1700000'},
       {'journal_id': '6885a9dcb0b52d2e447eb28e', 'cash_left': '1495000', 'terminal_income': '1650000'},
       {'cash_left': '14950000', 'terminal_income': '1650000', 'journal_id': '6885a9dcb0b52d2e447eb28e'},
       {'journal_id': '68871c6bb0b52d2e447eb2b6', 'cash_left': '13400000', 'terminal_income': '1580000'},
       {'journal_id': '6887406eb0b52d2e447eb2b9', 'cash_left': '1500000', 'terminal_income': '2100000'},
       {'journal_id': '6888bf7ab0b52d2e447eb2d3', 'cash_left': '500000', 'terminal_income': '1265000'},
       {'journal_id': '68887cefb0b52d2e447eb2cb', 'cash_left': '20000', 'terminal_income': '1800000'},
       {'terminal_income': '1050000', 'journal_id': '6889a26ab0b52d2e447eb2df', 'cash_left': '7000000'},
       {'journal_id': '6889a26ab0b52d2e447eb2df', 'cash_left': '7000000', 'terminal_income': '1050000'},
       {'journal_id': '6889eeecb0b52d2e447eb2e7', 'cash_left': '5000000', 'terminal_income': '1000000'},
       {'journal_id': '688b0626b0b52d2e447eb2f6', 'cash_left': '4600000', 'terminal_income': '1850000'},
       {'journal_id': '688b1786b0b52d2e447eb2fa', 'cash_left': '1550000', 'terminal_income': '4800000'},
       {'journal_id': '688c6754b0b52d2e447eb30b', 'cash_left': '10000', 'terminal_income': '1700000'},
       {'journal_id': '688c6d2fb0b52d2e447eb30e', 'cash_left': '3600000', 'terminal_income': '908000'},
       {'journal_id': '688c6754b0b52d2e447eb30b', 'cash_left': '10000', 'terminal_income': '1700000'},
       {'journal_id': '688db4dbb0b52d2e447eb31e', 'cash_left': '5100000', 'terminal_income': '2600000'},
       {'journal_id': '688db7bab0b52d2e447eb321', 'cash_left': '6734000', 'terminal_income': '2400000'},
       {'journal_id': '688db4dbb0b52d2e447eb31e', 'cash_left': '5400000', 'terminal_income': '3275000'},
       {'journal_id': '688ef233b0b52d2e447eb335', 'cash_left': '6550000', 'terminal_income': '2760000'},
       {'journal_id': '688ef23bb0b52d2e447eb337', 'cash_left': '7150000', 'terminal_income': '1900000'},
       {'journal_id': '689034ccb0b52d2e447eb343', 'cash_left': '6810000', 'terminal_income': '288000'},
       {'journal_id': '68906ef6b0b52d2e447eb348', 'cash_left': '7060000', 'terminal_income': '2400000'},
       {'journal_id': '6891bac3b0b52d2e447eb359', 'cash_left': '3200000', 'terminal_income': '2000000'},
       {'terminal_income': '1150000', 'journal_id': '6891c910b0b52d2e447eb35c', 'cash_left': '6200000'},
       {'journal_id': '68930a3eb0b52d2e447eb372', 'cash_left': '1950000', 'terminal_income': '1500000'},
       {'journal_id': '6892eddeb0b52d2e447eb36f', 'cash_left': '2100000', 'terminal_income': '1740000'},
       {'journal_id': '6891c910b0b52d2e447eb35c', 'cash_left': '6500000', 'terminal_income': '3200000'},
       {'journal_id': '6891c910b0b52d2e447eb35c', 'cash_left': '5500000', 'terminal_income': '2800000'},
       {'journal_id': '68943c47b0b52d2e447eb38a', 'cash_left': '10050000', 'terminal_income': '2067000'},
       {'terminal_income': '1000', 'journal_id': '68944703b0b52d2e447eb38d', 'cash_left': '8960000'},
       {'terminal_income': '2500000', 'journal_id': '68944703b0b52d2e447eb38d', 'cash_left': '8960000'},
       {'journal_id': '689570f2b0b52d2e447eb3a1', 'cash_left': '500000', 'terminal_income': '2450000'},
       {'journal_id': '689591d5b0b52d2e447eb3a6', 'cash_left': '1800000', 'terminal_income': '1500000'},
       {'journal_id': '6897144f26dd6c6e8fbfbbac', 'cash_left': '3750000', 'terminal_income': '2500000'},
       {'cash_left': '1200000', 'terminal_income': '3850000', 'journal_id': '6896efb326dd6c6e8fbfbba6'},
       {'journal_id': '6898b29e8a73bea8d51b7897', 'cash_left': '9400000', 'terminal_income': '3600000'},
       {'journal_id': '689833658a73bea8d51b7892', 'cash_left': '10200000', 'terminal_income': '2536000'},
       {'terminal_income': '1700000', 'journal_id': '6899fbe7b5e3e1a6443c210d', 'cash_left': '10150000'},
       {'journal_id': '6899fbe7b5e3e1a6443c210d', 'cash_left': '10150000', 'terminal_income': '1700000'},
       {'journal_id': '68997bc3b5e3e1a6443c2085', 'cash_left': '10150000', 'terminal_income': '1700000'},
       {'journal_id': '6899d58cb5e3e1a6443c20e1', 'cash_left': '2900000', 'terminal_income': '2950000'},
       {'journal_id': '6899fbe7b5e3e1a6443c210d', 'cash_left': '4500000', 'terminal_income': '4800000'},
       {'journal_id': '689ae2670512718bb8e0ae4e', 'cash_left': '3680000', 'terminal_income': '1900000'},
       {'journal_id': '689ae2670512718bb8e0ae4e', 'cash_left': '3980000', 'terminal_income': '1900000'},
       {'cash_left': '7720000', 'terminal_income': '2350000', 'journal_id': '689c0ad90512718bb8e0ae6b'},
       {'journal_id': '689d6d6d0512718bb8e0ae7d', 'cash_left': '6605000', 'terminal_income': '2500000'},
       {'terminal_income': '2500000', 'journal_id': '689cd1720512718bb8e0ae78', 'cash_left': '6605000'},
       {'journal_id': '689d5c700512718bb8e0ae7a', 'cash_left': '4900000', 'terminal_income': '1970000'},
       {'cash_left': '8400000', 'terminal_income': '1143000', 'journal_id': '689eb5060512718bb8e0ae96'},
       {'journal_id': '689f3f080512718bb8e0ae9f', 'cash_left': '3040000', 'terminal_income': '1100000'},
       {'journal_id': '68a03e050512718bb8e0aea9', 'cash_left': '2100000', 'terminal_income': '2600000'},
       {'journal_id': '68a06ba70512718bb8e0aeaf', 'cash_left': '8835000', 'terminal_income': '2500000'},
       {'journal_id': '68a06ba70512718bb8e0aeaf', 'cash_left': '9075000', 'terminal_income': '2500000'},
       {'cash_left': '12300000', 'terminal_income': '2980000', 'journal_id': '68a1dec9601d9fd442be5814'},
       {'cash_left': '12700000', 'terminal_income': '2980000', 'journal_id': '68a1dec9601d9fd442be5814'},
       {'journal_id': '68a1dec3601d9fd442be5812', 'cash_left': '11100000', 'terminal_income': '4140000'},
       {'journal_id': '68a1dec3601d9fd442be5812', 'cash_left': '12100000', 'terminal_income': '4140000'},
       {'cash_left': '6800000', 'terminal_income': '2350000', 'journal_id': '68a2b0a7601d9fd442be5820'},
       {'journal_id': '68a320e4601d9fd442be5827', 'cash_left': '1750000', 'terminal_income': '1700000'},
       {'journal_id': '68a41c64601d9fd442be5833', 'cash_left': '1220000', 'terminal_income': '1700000'},
       {'journal_id': '68a42a07601d9fd442be5839', 'cash_left': '10775000', 'terminal_income': '1440000'},
       {'journal_id': '68a41c64601d9fd442be5833', 'cash_left': '1220000', 'terminal_income': '1700000'},
       {'cash_left': '8400000', 'terminal_income': '2550000', 'journal_id': '68a5412b601d9fd442be5850'},
       {'journal_id': '68a5632b601d9fd442be5856', 'cash_left': '586', 'terminal_income': '2400000'},
       {'terminal_income': '2400000', 'journal_id': '68a5632b601d9fd442be5856', 'cash_left': '5870000'},
       {'cash_left': '3820000', 'terminal_income': '2000000', 'journal_id': '68a6c88f601d9fd442be5874'},
       {'journal_id': '68a6c88f601d9fd442be5874', 'cash_left': '3820000', 'terminal_income': '2000000'},
       {'journal_id': '68a6a54f601d9fd442be586b', 'cash_left': '5800000', 'terminal_income': '1900000'},
       {'journal_id': '68a833bb601d9fd442be588f', 'cash_left': '2150000', 'terminal_income': '2900000'},
       {'cash_left': '1200000', 'terminal_income': '3650000', 'journal_id': '68a7f2d4601d9fd442be5889'},
       {'journal_id': '68a95e9b601d9fd442be58a6', 'cash_left': '6350000', 'terminal_income': '1850000'},
       {'journal_id': '68a9b0bb601d9fd442be58ad', 'cash_left': '6650000', 'terminal_income': '1500000'},
       {'journal_id': '68a9b0bb601d9fd442be58ad', 'cash_left': '1500000', 'terminal_income': '6650000'},
       {'terminal_income': '1500000', 'journal_id': '68a9b0bb601d9fd442be58ad', 'cash_left': '6650000'},
       {'journal_id': '689d6d6d0512718bb8e0ae7d', 'cash_left': '1', 'terminal_income': '1'},
       {'journal_id': '68aa9214601d9fd442be58b9', 'cash_left': '12300000', 'terminal_income': '3050000'},
       {'journal_id': '68ab2f93601d9fd442be58c9', 'cash_left': '7640000', 'terminal_income': '2700000'},
       {'journal_id': '68ac0340601d9fd442be58d0', 'cash_left': '1500000', 'terminal_income': '7950000'},
       {'journal_id': '68ac05dc601d9fd442be58d3', 'cash_left': '3200000', 'terminal_income': '2600000'},
       {'terminal_income': '1650000', 'journal_id': '68ad3bff601d9fd442be58e3', 'cash_left': '1900000'},
       {'journal_id': '68ad3bff601d9fd442be58e3', 'cash_left': '1900000', 'terminal_income': '1650000'},
       {'journal_id': '68ad3bff601d9fd442be58e3', 'cash_left': '1900000', 'terminal_income': '1650000'},
       {'journal_id': '68ad6256601d9fd442be58e7', 'cash_left': '4300000', 'terminal_income': '2855000'},
       {'cash_left': '6855000', 'terminal_income': '2700000', 'journal_id': '68aef67fd11d33b0392abb53'},
       {'journal_id': '68aee036d11d33b0392abb4e', 'cash_left': '5200000', 'terminal_income': '680000'},
       {'cash_left': '5000000', 'terminal_income': '1040000', 'journal_id': '68b05eb3d11d33b0392abb68'},
       {'terminal_income': '1000000', 'journal_id': '68aff8e3d11d33b0392abb64', 'cash_left': '7450000'},
       {'journal_id': '68b16a0ed11d33b0392abb74', 'cash_left': '1955000', 'terminal_income': '2000000'},
       {'journal_id': '68b15e53d11d33b0392abb71', 'cash_left': '1650000', 'terminal_income': '4339000'},
       {'journal_id': '68b2e4dfd11d33b0392abb92', 'cash_left': '300000', 'terminal_income': '2500000'},
       {'journal_id': '68b2e4dfd11d33b0392abb92', 'cash_left': '300000', 'terminal_income': '2500000'},
       {'cash_left': '3400000', 'terminal_income': '2700000', 'journal_id': '68b2a712d11d33b0392abb89'},
       {'journal_id': '68b46fafd11d33b0392abbab', 'cash_left': '6900000', 'terminal_income': '2300000'},
       {'journal_id': '68b3d11fd11d33b0392abba3', 'cash_left': '3650000', 'terminal_income': '3350000'},
       {'journal_id': '68b587cdd11d33b0392abbb7', 'cash_left': '10000000', 'terminal_income': '4500000'},
       {'journal_id': '68b54bd4d11d33b0392abbb3', 'cash_left': '6623000', 'terminal_income': '2240000'},
       {'journal_id': '68b6cf3fd11d33b0392abbcd', 'cash_left': '1900000', 'terminal_income': '2200000'},
       {'journal_id': '68b68d4bd11d33b0392abbc3', 'cash_left': '1800000', 'terminal_income': '1850000'},
       {'journal_id': '68b7ffaed11d33b0392abbdd', 'cash_left': '3350000', 'terminal_income': '3060000'},
       {'journal_id': '68b7ffaed11d33b0392abbdd', 'cash_left': '3350000', 'terminal_income': '3060000'},
       {'journal_id': '68b7ffaed11d33b0392abbdd', 'cash_left': '3900000', 'terminal_income': '3060000'},
       {'journal_id': '68b80b1cd11d33b0392abbe2', 'cash_left': '900000', 'terminal_income': '3300000'},
       {'journal_id': '68b95c1fd11d33b0392abbf8', 'cash_left': '3350000', 'terminal_income': '3040000'},
       {'journal_id': '68b93356d11d33b0392abbf6', 'cash_left': '5000000', 'terminal_income': '3500000'},
       {'journal_id': '68b95c1fd11d33b0392abbf8', 'cash_left': '4000000', 'terminal_income': '3040000'},
       {'journal_id': '68bb0038a629900f2cd41743', 'cash_left': '1000000', 'terminal_income': '1600000'},
       {'cash_left': '700000', 'terminal_income': '1600000', 'journal_id': '68bb0038a629900f2cd41743'},
       {'journal_id': '68badc83a629900f2cd41739', 'cash_left': '2750000', 'terminal_income': '2850000'},
       {'journal_id': '68bbd48ba629900f2cd41752', 'cash_left': '3590000', 'terminal_income': '4400000'},
       {'terminal_income': '2850000', 'journal_id': '68bbf28ca629900f2cd41759', 'cash_left': '5200000'},
       {'cash_left': '3300000', 'terminal_income': '2850000', 'journal_id': '68bbf28ca629900f2cd41759'},
       {'cash_left': '9470000', 'terminal_income': '2800000', 'journal_id': '68bd686ba629900f2cd41767'},
       {'journal_id': '68bd8087a629900f2cd4176a', 'cash_left': '9100000', 'terminal_income': '3250000'},
       {'terminal_income': '1550000', 'journal_id': '68be84126a5214dd66b59028', 'cash_left': '1900000'},
       {'journal_id': '68beeaac6a5214dd66b5902d', 'cash_left': '8950000', 'terminal_income': '2050000'},
       {'journal_id': '68bfed676a5214dd66b59037', 'cash_left': '6350000', 'terminal_income': '3880000'},
       {'journal_id': '68c053ca6a5214dd66b59040', 'cash_left': '8500000', 'terminal_income': '1730000'},
       {'journal_id': '68c053ca6a5214dd66b59040', 'cash_left': '8500000', 'terminal_income': '1730000'},
       {'journal_id': '68c155466a5214dd66b5904c', 'cash_left': '500000', 'terminal_income': '2615000'},
       {'journal_id': '68c155466a5214dd66b5904c', 'cash_left': '500000', 'terminal_income': '2615000'},
       {'cash_left': '8250000', 'terminal_income': '2400000', 'journal_id': '68c1555d6a5214dd66b5904f'},
       {'terminal_income': '2800000', 'journal_id': '68c2a14f6a5214dd66b59063', 'cash_left': '9150000'},
       {'journal_id': '68c2655d6a5214dd66b5905b', 'cash_left': '9150000', 'terminal_income': '2800000'},

In [46]:
df = df.drop(columns=["_id"])

,user_id,action,data,ip,date,status
215,aslon,create_journal,{'branchnameorid': 'aadee444-306d-48e1-aa5c-50...,172.18.0.1,2025-07-06 13:09:16.214,200
186,aslon,create_journal,{'branchnameorid': 'aadee444-306d-48e1-aa5c-50...,172.18.0.1,2025-07-06 13:09:28.362,200
216,aslon,login_success,{'error': 'Invalid password'},172.18.0.1,2025-07-06 13:27:29.938,200
0,aslon,login_success,{'error': 'Invalid password'},172.18.0.1,2025-07-06 13:27:34.412,200
73,jaloliddin,login_success,{'error': 'Invalid password'},172.18.0.1,2025-07-06 14:48:33.025,200
...,...,...,...,...,...,...
6304,umidx,create_transaction,"{'transactionbase': {'amount': 1200000, 'descr...",100.64.0.15,2026-05-30 15:50:25.249,200
6305,umidx,create_transaction,"{'transactionbase': {'amount': 1200000, 'descr...",100.64.0.7,2026-05-30 15:53:16.650,200
6306,umidx,close_journal,"{'journal_id': '6a1aa93010b6126747f91383', 'ca...",100.64.0.7,2026-05-30 15:54:36.310,200
6307,umidx,create_journal,{'branchnameorid': 'aadee444-306d-48e1-aa5c-50...,100.64.0.13,2026-05-31 05:34:07.397,200
6308,umidx,create_transaction,"{'transactionbase': {'amount': 130000, 'descri...",100.64.0.13,2026-05-31 05:34:27.519,200

In [ ]:
df.to_json(
    "activities.jsonl", 
    orient="records", 
    lines=True
2)

/var/folders/3z/114t1ckn7y18rzrz_m6kfkt80000gn/T/ipykernel_65755/1100017637.py:1: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

OverflowError: Overlong 2 byte UTF-8 sequence detected when encoding string